/** Generated by scripts/build-texts.py — do not edit. */
export const BOOKS = [
  {
    "nr": 1,
    "id": "genese",
    "title": "Livre de la Genèse",
    "short": "Gn",
    "testament": "at",
    "section": "torah",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 2,
    "id": "exode",
    "title": "Livre de l'Exode",
    "short": "Ex",
    "testament": "at",
    "section": "torah",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 3,
    "id": "levitique",
    "title": "Livre du Lévitique",
    "short": "Lv",
    "testament": "at",
    "section": "torah",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 4,
    "id": "nombres",
    "title": "Livre des Nombres",
    "short": "Nb",
    "testament": "at",
    "section": "torah",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 5,
    "id": "deuteronome",
    "title": "Livre du Deutéronome",
    "short": "Dt",
    "testament": "at",
    "section": "torah",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 6,
    "id": "josue",
    "title": "Livre de Josué",
    "short": "Jos",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 7,
    "id": "juges",
    "title": "Livre des Juges",
    "short": "Jg",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 8,
    "id": "1-samuel",
    "title": "Premier livre de Samuel",
    "short": "1 S",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 9,
    "id": "2-samuel",
    "title": "Second livre de Samuel",
    "short": "2 S",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 10,
    "id": "1-rois",
    "title": "Premier livre des Rois",
    "short": "1 R",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 11,
    "id": "2-rois",
    "title": "Second livre des Rois",
    "short": "2 R",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 12,
    "id": "esaie",
    "title": "Livre d'Ésaïe",
    "short": "Es",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 13,
    "id": "jeremie",
    "title": "Livre de Jérémie",
    "short": "Jr",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 14,
    "id": "ezechiel",
    "title": "Livre d'Ézéchiel",
    "short": "Ez",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 15,
    "id": "osee",
    "title": "Livre d'Osée",
    "short": "Os",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 16,
    "id": "joel",
    "title": "Livre de Joël",
    "short": "Jl",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 17,
    "id": "amos",
    "title": "Livre d'Amos",
    "short": "Am",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 18,
    "id": "abdias",
    "title": "Livre d'Abdias",
    "short": "Ab",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 19,
    "id": "jonas",
    "title": "Livre de Jonas",
    "short": "Jon",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 20,
    "id": "michee",
    "title": "Livre de Michée",
    "short": "Mi",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 21,
    "id": "nahum",
    "title": "Livre de Nahum",
    "short": "Na",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 22,
    "id": "habacuc",
    "title": "Livre d'Habacuc",
    "short": "Ha",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 23,
    "id": "sophonie",
    "title": "Livre de Sophonie",
    "short": "So",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 24,
    "id": "aggee",
    "title": "Livre d'Aggée",
    "short": "Ag",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 25,
    "id": "zacharie",
    "title": "Livre de Zacharie",
    "short": "Za",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 26,
    "id": "malachie",
    "title": "Livre de Malachie",
    "short": "Ml",
    "testament": "at",
    "section": "neviim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 27,
    "id": "psaumes",
    "title": "Livre des Psaumes",
    "short": "Ps",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 28,
    "id": "proverbes",
    "title": "Livre des Proverbes",
    "short": "Pr",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 29,
    "id": "job",
    "title": "Livre de Job",
    "short": "Jb",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 30,
    "id": "cantique",
    "title": "Cantique des cantiques",
    "short": "Ct",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 31,
    "id": "ruth",
    "title": "Livre de Ruth",
    "short": "Rt",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 32,
    "id": "lamentations",
    "title": "Lamentations de Jérémie",
    "short": "Lm",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 33,
    "id": "ecclesiaste",
    "title": "L'Ecclésiaste",
    "short": "Ec",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 34,
    "id": "esther",
    "title": "Livre d'Esther",
    "short": "Est",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 35,
    "id": "daniel",
    "title": "Livre de Daniel",
    "short": "Dn",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 36,
    "id": "esdras",
    "title": "Livre d'Esdras",
    "short": "Esd",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 37,
    "id": "nehemie",
    "title": "Livre de Néhémie",
    "short": "Né",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 38,
    "id": "1-chroniques",
    "title": "Premier livre des Chroniques",
    "short": "1 Ch",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 39,
    "id": "2-chroniques",
    "title": "Second livre des Chroniques",
    "short": "2 Ch",
    "testament": "at",
    "section": "ketuvim",
    "canons": [
      "jewish",
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 40,
    "id": "tobie",
    "title": "Livre de Tobie",
    "short": "Tb",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 41,
    "id": "judith",
    "title": "Livre de Judith",
    "short": "Jdt",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 42,
    "id": "sagesse",
    "title": "Livre de la Sagesse",
    "short": "Sg",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 43,
    "id": "siracide",
    "title": "Siracide (Ecclésiastique)",
    "short": "Si",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 44,
    "id": "baruch",
    "title": "Livre de Baruch",
    "short": "Ba",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 45,
    "id": "1-maccabees",
    "title": "Premier livre des Maccabées",
    "short": "1 M",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 46,
    "id": "2-maccabees",
    "title": "Second livre des Maccabées",
    "short": "2 M",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 47,
    "id": "3-maccabees",
    "title": "Troisième livre des Maccabées",
    "short": "3 M",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "orthodox"
    ]
  },
  {
    "nr": 48,
    "id": "4-maccabees",
    "title": "Quatrième livre des Maccabées",
    "short": "4 M",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "orthodox"
    ]
  },
  {
    "nr": 49,
    "id": "psaume-151",
    "title": "Psaume 151",
    "short": "Ps151",
    "testament": "at",
    "section": "deuterocanoniques",
    "canons": [
      "orthodox"
    ]
  },
  {
    "nr": 50,
    "id": "matthieu",
    "title": "Évangile selon saint Matthieu",
    "short": "Mt",
    "testament": "nt",
    "section": "evangiles",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 51,
    "id": "marc",
    "title": "Évangile selon saint Marc",
    "short": "Mc",
    "testament": "nt",
    "section": "evangiles",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 52,
    "id": "luc",
    "title": "Évangile selon saint Luc",
    "short": "Lc",
    "testament": "nt",
    "section": "evangiles",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 53,
    "id": "jean",
    "title": "Évangile selon saint Jean",
    "short": "Jn",
    "testament": "nt",
    "section": "evangiles",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 54,
    "id": "actes",
    "title": "Actes des Apôtres",
    "short": "Ac",
    "testament": "nt",
    "section": "actes",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 55,
    "id": "romains",
    "title": "Lettre de saint Paul Apôtre aux Romains",
    "short": "Rm",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 56,
    "id": "1-corinthiens",
    "title": "Première lettre de saint Paul Apôtre aux Corinthiens",
    "short": "1 Co",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 57,
    "id": "2-corinthiens",
    "title": "Seconde lettre de saint Paul Apôtre aux Corinthiens",
    "short": "2 Co",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 58,
    "id": "galates",
    "title": "Lettre de saint Paul Apôtre aux Galates",
    "short": "Ga",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 59,
    "id": "ephesiens",
    "title": "Lettre de saint Paul Apôtre aux Éphésiens",
    "short": "Ép",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 60,
    "id": "philippiens",
    "title": "Lettre de saint Paul Apôtre aux Philippiens",
    "short": "Ph",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 61,
    "id": "colossiens",
    "title": "Lettre de saint Paul Apôtre aux Colossiens",
    "short": "Col",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 62,
    "id": "1-thessaloniciens",
    "title": "Première lettre de saint Paul Apôtre aux Thessaloniciens",
    "short": "1 Th",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 63,
    "id": "2-thessaloniciens",
    "title": "Seconde lettre de saint Paul Apôtre aux Thessaloniciens",
    "short": "2 Th",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 64,
    "id": "1-timothee",
    "title": "Première lettre de saint Paul Apôtre à Timothée",
    "short": "1 Tm",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 65,
    "id": "2-timothee",
    "title": "Seconde lettre de saint Paul Apôtre à Timothée",
    "short": "2 Tm",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 66,
    "id": "tite",
    "title": "Lettre de saint Paul Apôtre à Tite",
    "short": "Tt",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 67,
    "id": "philemon",
    "title": "Lettre de saint Paul Apôtre à Philémon",
    "short": "Phm",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 68,
    "id": "hebreux",
    "title": "Lettre aux Hébreux",
    "short": "Hé",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 69,
    "id": "jacques",
    "title": "Lettre de saint Jacques",
    "short": "Jc",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 70,
    "id": "1-pierre",
    "title": "Première lettre de saint Pierre Apôtre",
    "short": "1 P",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 71,
    "id": "2-pierre",
    "title": "Seconde lettre de saint Pierre Apôtre",
    "short": "2 P",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 72,
    "id": "1-jean",
    "title": "Première lettre de saint Jean",
    "short": "1 Jn",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 73,
    "id": "2-jean",
    "title": "Seconde lettre de saint Jean",
    "short": "2 Jn",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 74,
    "id": "3-jean",
    "title": "Troisième lettre de saint Jean",
    "short": "3 Jn",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 75,
    "id": "jude",
    "title": "Lettre de saint Jude",
    "short": "Jude",
    "testament": "nt",
    "section": "epitres",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  },
  {
    "nr": 76,
    "id": "apocalypse",
    "title": "Apocalypse de saint Jean",
    "short": "Ap",
    "testament": "nt",
    "section": "apocalypse",
    "canons": [
      "protestant",
      "catholic",
      "orthodox"
    ]
  }
];

export const SECTIONS = [
  {
    "id": "torah",
    "testament": "at",
    "label": "Pentateuque"
  },
  {
    "id": "neviim",
    "testament": "at",
    "label": "Prophètes"
  },
  {
    "id": "ketuvim",
    "testament": "at",
    "label": "Écrits"
  },
  {
    "id": "deuterocanoniques",
    "testament": "at",
    "label": "Deutérocanoniques"
  },
  {
    "id": "evangiles",
    "testament": "nt",
    "label": "Évangiles"
  },
  {
    "id": "actes",
    "testament": "nt",
    "label": "Actes"
  },
  {
    "id": "epitres",
    "testament": "nt",
    "label": "Épîtres"
  },
  {
    "id": "apocalypse",
    "testament": "nt",
    "label": "Apocalypse"
  }
];

export const TOC_SECTIONS = [
  {
    "id": "pentateuque",
    "testament": "at",
    "label": "Pentateuque",
    "ids": [
      "genese",
      "exode",
      "levitique",
      "nombres",
      "deuteronome"
    ]
  },
  {
    "id": "historiques",
    "testament": "at",
    "label": "Livres historiques",
    "ids": [
      "josue",
      "juges",
      "ruth",
      "1-samuel",
      "2-samuel",
      "1-rois",
      "2-rois",
      "1-chroniques",
      "2-chroniques",
      "esdras",
      "nehemie",
      "tobie",
      "judith",
      "esther",
      "1-maccabees",
      "2-maccabees",
      "3-maccabees",
      "4-maccabees"
    ]
  },
  {
    "id": "poetiques",
    "testament": "at",
    "label": "Livres poétiques",
    "ids": [
      "job",
      "psaumes",
      "psaume-151",
      "proverbes",
      "ecclesiaste",
      "cantique",
      "sagesse",
      "siracide"
    ]
  },
  {
    "id": "prophetes",
    "testament": "at",
    "label": "Prophètes",
    "ids": [
      "esaie",
      "jeremie",
      "lamentations",
      "baruch",
      "ezechiel",
      "daniel",
      "osee",
      "joel",
      "amos",
      "abdias",
      "jonas",
      "michee",
      "nahum",
      "habacuc",
      "sophonie",
      "aggee",
      "zacharie",
      "malachie"
    ]
  },
  {
    "id": "evangiles",
    "testament": "nt",
    "label": "Évangiles",
    "ids": [
      "matthieu",
      "marc",
      "luc",
      "jean"
    ]
  },
  {
    "id": "actes",
    "testament": "nt",
    "label": "Actes",
    "ids": [
      "actes"
    ]
  },
  {
    "id": "epitres",
    "testament": "nt",
    "label": "Épîtres",
    "ids": [
      "romains",
      "1-corinthiens",
      "2-corinthiens",
      "galates",
      "ephesiens",
      "philippiens",
      "colossiens",
      "1-thessaloniciens",
      "2-thessaloniciens",
      "1-timothee",
      "2-timothee",
      "tite",
      "philemon",
      "hebreux",
      "jacques",
      "1-pierre",
      "2-pierre",
      "1-jean",
      "2-jean",
      "3-jean",
      "jude"
    ]
  },
  {
    "id": "apocalypse",
    "testament": "nt",
    "label": "Apocalypse",
    "ids": [
      "apocalypse"
    ]
  }
];

export const VERSIONS = {
  "segond-1910": {
    "id": "segond-1910",
    "label": "Louis Segond 1910",
    "name": "Louis Segond",
    "blurb": "Traduction de Louis Segond · 1910",
    "year": 1910,
    "lang": "fr",
    "license": "public-domain",
    "source": "Louis Segond 1910",
    "abbreviation": "ls1910",
    "canon": "protestant",
    "at": "Ancien Testament",
    "nt": "Nouveau Testament"
  },
  "martin": {
    "id": "martin",
    "label": "David Martin 1744",
    "name": "David Martin",
    "blurb": "Traduction de David Martin · 1744",
    "year": 1744,
    "lang": "fr",
    "license": "public-domain",
    "source": "David Martin (rév. Pierre Roques)",
    "abbreviation": "martin",
    "canon": "protestant",
    "at": "Ancien Testament",
    "nt": "Nouveau Testament"
  },
  "darby": {
    "id": "darby",
    "label": "John Nelson Darby",
    "name": "J. N. Darby",
    "blurb": "Traduction de J. N. Darby · 1885",
    "year": 1885,
    "lang": "fr",
    "license": "public-domain",
    "source": "J.N. Darby (Bible complète)",
    "abbreviation": "darby",
    "canon": "protestant",
    "at": "Ancien Testament",
    "nt": "Nouveau Testament"
  },
  "ostervald": {
    "id": "ostervald",
    "label": "Ostervald",
    "name": "Ostervald",
    "blurb": "Traduction d'Ostervald · 1744",
    "year": 1744,
    "lang": "fr",
    "license": "public-domain",
    "source": "Jean-Frédéric Ostervald",
    "abbreviation": "ostervald",
    "canon": "protestant",
    "at": "Ancien Testament",
    "nt": "Nouveau Testament"
  },
  "crampon": {
    "id": "crampon",
    "label": "Crampon 1923",
    "name": "Augustin Crampon",
    "blurb": "Traduction d'Augustin Crampon · 1923",
    "year": 1923,
    "lang": "fr",
    "license": "public-domain",
    "source": "Augustin Crampon",
    "abbreviation": "crampon",
    "canon": "catholic",
    "at": "Ancien Testament",
    "nt": "Nouveau Testament"
  },
  "vulgate": {
    "id": "vulgate",
    "label": "Vulgate (Clementine)",
    "name": "Vulgata Clementina",
    "blurb": "Vulgata Clementina · 1592",
    "year": 1592,
    "lang": "la",
    "license": "public-domain",
    "source": "Vulgata Clementina",
    "abbreviation": "vulgate",
    "canon": "catholic",
    "at": "Vetus Testamentum",
    "nt": "Novum Testamentum"
  },
  "septante": {
    "id": "septante",
    "label": "Septante (LXX)",
    "name": "Septante (LXX)",
    "blurb": "Οἱ Ἑβδομήκοντα (LXX)",
    "year": -250,
    "year_label": "-250 av. J.C",
    "lang": "el",
    "license": "public-domain",
    "source": "Septante",
    "abbreviation": "lxx",
    "canon": "orthodox",
    "at": "Παλαιὰ Διαθήκη",
    "nt": "Καινὴ Διαθήκη"
  },
  "textusreceptus": {
    "id": "textusreceptus",
    "label": "Textus Receptus",
    "name": "Textus Receptus",
    "blurb": "Textus Receptus · 1550",
    "year": 1550,
    "lang": "el",
    "license": "public-domain",
    "source": "Textus Receptus (Stephanus)",
    "abbreviation": "textusreceptus",
    "canon": "protestant",
    "at": "Παλαιὰ Διαθήκη",
    "nt": "Καινὴ Διαθήκη"
  },
  "tischendorf": {
    "id": "tischendorf",
    "label": "Tischendorf",
    "name": "Tischendorf",
    "blurb": "Tischendorf · 1872",
    "year": 1872,
    "lang": "el",
    "license": "public-domain",
    "source": "Constantin von Tischendorf (8e éd.)",
    "abbreviation": "tischendorf",
    "canon": "protestant",
    "at": "Παλαιὰ Διαθήκη",
    "nt": "Καινὴ Διαθήκη"
  },
  "westcotthort": {
    "id": "westcotthort",
    "label": "Westcott-Hort",
    "name": "Westcott & Hort",
    "blurb": "Westcott & Hort · 1881",
    "year": 1881,
    "lang": "el",
    "license": "public-domain",
    "source": "Westcott & Hort",
    "abbreviation": "westcotthort",
    "canon": "protestant",
    "at": "Παλαιὰ Διαθήκη",
    "nt": "Καινὴ Διαθήκη"
  },
  "moderngreek": {
    "id": "moderngreek",
    "label": "Grec moderne",
    "name": "Grec moderne",
    "blurb": "Ἡ Ἁγία Γραφή · 1850",
    "year": 1850,
    "lang": "el",
    "license": "public-domain",
    "source": "Neophytos Vamvas (1850)",
    "abbreviation": "moderngreek",
    "canon": "protestant",
    "at": "Παλαιὰ Διαθήκη",
    "nt": "Καινὴ Διαθήκη"
  },
  "leningrad": {
    "id": "leningrad",
    "label": "Codex Leningradensis",
    "name": "הקודקס הלנינגרדי",
    "blurb": "הקודקס הלנינגרדי",
    "year": 1008,
    "lang": "he",
    "license": "public-domain",
    "source": "Unicode/XML Leningrad Codex (UXLC 2.5)",
    "abbreviation": "leningrad",
    "canon": "jewish",
    "at": "תנ״ך",
    "nt": "הברית החדשה"
  },
  "kjv": {
    "id": "kjv",
    "label": "King James Version",
    "name": "King James Version",
    "blurb": "King James Version",
    "year": 1769,
    "lang": "en",
    "license": "Public domain (Crown letters patent apply within the UK)",
    "source": "https://ebible.org/find/details.php?id=eng-kjv",
    "abbreviation": "kjv",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "web": {
    "id": "web",
    "label": "World English Bible",
    "name": "World English Bible",
    "blurb": "World English Bible",
    "year": 2020,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=engwebp",
    "abbreviation": "web",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "asv": {
    "id": "asv",
    "label": "American Standard Version",
    "name": "American Standard Version",
    "blurb": "American Standard Version",
    "year": 1901,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=eng-asv",
    "abbreviation": "asv",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "ylt": {
    "id": "ylt",
    "label": "Young's Literal Translation",
    "name": "Young's Literal Translation",
    "blurb": "Young's Literal Translation",
    "year": 1898,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=engylt",
    "abbreviation": "ylt",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "darby-en": {
    "id": "darby-en",
    "label": "Darby Translation",
    "name": "Darby Translation",
    "blurb": "Darby Translation",
    "year": 1890,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=engDBY",
    "abbreviation": "darby-en",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "bbe": {
    "id": "bbe",
    "label": "Bible in Basic English",
    "name": "Bible in Basic English",
    "blurb": "Bible in Basic English",
    "year": 1949,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=engBBE",
    "abbreviation": "bbe",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "diodati": {
    "id": "diodati",
    "label": "Diodati 1649",
    "name": "Diodati 1649",
    "blurb": "Diodati 1649",
    "year": 1649,
    "lang": "it",
    "license": "Public domain",
    "source": "https://getbible.net",
    "abbreviation": "diodati",
    "canon": "protestant",
    "at": "Antico Testamento",
    "nt": "Nuovo Testamento"
  },
  "rv1909": {
    "id": "rv1909",
    "label": "Reina-Valera 1909",
    "name": "Reina-Valera 1909",
    "blurb": "Reina-Valera 1909",
    "year": 1909,
    "lang": "es",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=spaRV1909",
    "abbreviation": "rv1909",
    "canon": "protestant",
    "at": "Antiguo Testamento",
    "nt": "Nuevo Testamento"
  },
  "tr": {
    "id": "tr",
    "label": "Textus Receptus",
    "name": "Textus Receptus",
    "blurb": "Textus Receptus",
    "year": 1550,
    "lang": "el",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=grctr",
    "abbreviation": "tr",
    "canon": "protestant",
    "at": "Παλαιὰ Διαθήκη",
    "nt": "Καινὴ Διαθήκη"
  },
  "gnv": {
    "id": "gnv",
    "label": "Geneva Bible",
    "name": "Geneva Bible",
    "blurb": "Geneva Bible",
    "year": 1599,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=enggnv",
    "abbreviation": "gnv",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "dra": {
    "id": "dra",
    "label": "Douay-Rheims",
    "name": "Douay-Rheims",
    "blurb": "Douay-Rheims",
    "year": 1899,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=engDRA",
    "abbreviation": "dra",
    "canon": "catholic",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "riveduta": {
    "id": "riveduta",
    "label": "Riveduta",
    "name": "Riveduta",
    "blurb": "Riveduta",
    "year": 1927,
    "lang": "it",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=ita1927",
    "abbreviation": "riveduta",
    "canon": "protestant",
    "at": "Antico Testamento",
    "nt": "Nuovo Testamento"
  },
  "luther": {
    "id": "luther",
    "label": "Lutherbibel",
    "name": "Lutherbibel",
    "blurb": "Lutherbibel",
    "year": 1912,
    "lang": "de",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=deu1912",
    "abbreviation": "luther",
    "canon": "protestant",
    "at": "Altes Testament",
    "nt": "Neues Testament"
  },
  "pt": {
    "id": "pt",
    "label": "Bíblia Portuguesa Mundial",
    "name": "Bíblia Portuguesa Mundial",
    "blurb": "Bíblia Portuguesa Mundial",
    "year": 2018,
    "lang": "pt",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=porbrbsl",
    "abbreviation": "pt",
    "canon": "protestant",
    "at": "Antigo Testamento",
    "nt": "Novo Testamento"
  },
  "synodal": {
    "id": "synodal",
    "label": "Синодальный перевод",
    "name": "Синодальный перевод",
    "blurb": "Синодальный перевод",
    "year": 1876,
    "lang": "ru",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=russyn",
    "abbreviation": "synodal",
    "canon": "orthodox",
    "at": "Ветхий Завет",
    "nt": "Новый Завет"
  },
  "cuv": {
    "id": "cuv",
    "label": "新标点和合本",
    "name": "新标点和合本",
    "blurb": "新标点和合本",
    "year": 1919,
    "lang": "zh",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=cmn-cu89s",
    "abbreviation": "cuv",
    "canon": "protestant",
    "at": "旧约",
    "nt": "新约"
  },
  "vandyck": {
    "id": "vandyck",
    "label": "فان دايك",
    "name": "فان دايك",
    "blurb": "فان دايك",
    "year": 1865,
    "lang": "ar",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=arb-vd",
    "abbreviation": "vandyck",
    "canon": "protestant",
    "at": "العهد القديم",
    "nt": "العهد الجديد"
  },
  "kougo": {
    "id": "kougo",
    "label": "口語訳聖書",
    "name": "口語訳聖書",
    "blurb": "口語訳聖書",
    "year": 1955,
    "lang": "ja",
    "license": "Public domain",
    "source": "https://getbible.net",
    "abbreviation": "kougo",
    "canon": "protestant",
    "at": "旧約",
    "nt": "新約"
  },
  "norsk": {
    "id": "norsk",
    "label": "Bibelselskapet 1930",
    "name": "Bibelselskapet 1930",
    "blurb": "Bibelselskapet 1930",
    "year": 1930,
    "lang": "no",
    "license": "Public domain",
    "source": "https://getbible.net",
    "abbreviation": "norsk",
    "canon": "protestant",
    "at": "Det gamle testamente",
    "nt": "Det nye testamente"
  },
  "karoli": {
    "id": "karoli",
    "label": "Károli 1908",
    "name": "Károli 1908",
    "blurb": "Károli 1908",
    "year": 1908,
    "lang": "hu",
    "license": "Public domain",
    "source": "https://getbible.net",
    "abbreviation": "karoli",
    "canon": "protestant",
    "at": "Ószövetség",
    "nt": "Újszövetség"
  },
  "rv1885": {
    "id": "rv1885",
    "label": "English Revised Version",
    "name": "English Revised Version",
    "blurb": "English Revised Version",
    "year": 1885,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=eng-rv",
    "abbreviation": "rv1885",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "jps": {
    "id": "jps",
    "label": "JPS Tanakh 1917",
    "name": "JPS Tanakh 1917",
    "blurb": "JPS Tanakh 1917",
    "year": 1917,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=engjps",
    "abbreviation": "jps",
    "canon": "jewish",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "webster": {
    "id": "webster",
    "label": "Webster's Bible",
    "name": "Webster's Bible",
    "blurb": "Webster's Bible",
    "year": 1833,
    "lang": "en",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=engwebster",
    "abbreviation": "webster",
    "canon": "protestant",
    "at": "Old Testament",
    "nt": "New Testament"
  },
  "elberfelder": {
    "id": "elberfelder",
    "label": "Elberfelder 1905",
    "name": "Elberfelder 1905",
    "blurb": "Elberfelder 1905",
    "year": 1905,
    "lang": "de",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=deuelo",
    "abbreviation": "elberfelder",
    "canon": "protestant",
    "at": "Altes Testament",
    "nt": "Neues Testament"
  },
  "textbibel": {
    "id": "textbibel",
    "label": "Textbibel 1906",
    "name": "Textbibel 1906",
    "blurb": "Textbibel 1906",
    "year": 1906,
    "lang": "de",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=deutkw",
    "abbreviation": "textbibel",
    "canon": "protestant",
    "at": "Altes Testament",
    "nt": "Neues Testament"
  },
  "czech": {
    "id": "czech",
    "label": "Bible kralická (1613)",
    "name": "Bible kralická (1613)",
    "blurb": "Bible kralická (1613)",
    "year": 1613,
    "lang": "cs",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=ces1613",
    "abbreviation": "czech",
    "canon": "protestant",
    "at": "Starý zákon",
    "nt": "Nový zákon"
  },
  "serbian": {
    "id": "serbian",
    "label": "Sveto pismo (Karadžić–Daničić)",
    "name": "Sveto pismo (Karadžić–Daničić)",
    "blurb": "Sveto pismo (Karadžić–Daničić)",
    "year": 1868,
    "lang": "sr",
    "license": "Public domain",
    "source": "https://ebible.org/find/details.php?id=srp1865",
    "abbreviation": "serbian",
    "canon": "protestant",
    "at": "Стари завјет",
    "nt": "Нови завјет"
  },
  "dutch": {
    "id": "dutch",
    "label": "Statenvertaling (1637)",
    "name": "Statenvertaling (1637)",
    "blurb": "Statenvertaling (1637)",
    "year": 1637,
    "lang": "nl",
    "license": "Public domain",
    "source": "https://getbible.net",
    "abbreviation": "dutch",
    "canon": "protestant",
    "at": "Oude Testament",
    "nt": "Nieuwe Testament"
  },
  "swedish": {
    "id": "swedish",
    "label": "Svenska (1917)",
    "name": "Svenska (1917)",
    "blurb": "Svenska (1917)",
    "year": 1917,
    "lang": "sv",
    "license": "Public domain",
    "source": "https://getbible.net",
    "abbreviation": "swedish",
    "canon": "protestant",
    "at": "Gamla testamentet",
    "nt": "Nya testamentet"
  },
  "finnish": {
    "id": "finnish",
    "label": "Biblia (1776)",
    "name": "Biblia (1776)",
    "blurb": "Biblia (1776)",
    "year": 1776,
    "lang": "fi",
    "license": "Public domain",
    "source": "https://getbible.net",
    "abbreviation": "finnish",
    "canon": "protestant",
    "at": "Vanha testamentti",
    "nt": "Uusi testamentti"
  },
  "tagalog": {
    "id": "tagalog",
    "label": "Ang Dating Biblia (1905)",
    "name": "Ang Dating Biblia (1905)",
    "blurb": "Ang Dating Biblia (1905)",
    "year": 1905,
    "lang": "tl",
    "license": "Public domain",
    "source": "https://getbible.net",
    "abbreviation": "tagalog",
    "canon": "protestant",
    "at": "Lumang Tipan",
    "nt": "Bagong Tipan"
  },
  "qumran": {
    "id": "qumran",
    "label": "Qumrân",
    "name": "Qumrân",
    "blurb": "Martin Abegg, ETCBC, licence CC BY-NC 4.0",
    "lang": "fr",
    "license": "CC BY-NC 4.0",
    "source": "https://github.com/ETCBC/dss",
    "abbreviation": "qumran",
    "canon": "dss"
  }
};

export const BOOK_BY_ID = Object.fromEntries(BOOKS.map(b => [b.id, b]));
export const BOOK_BY_NR = Object.fromEntries(BOOKS.map(b => [b.nr, b]));
export const GOSPEL_IDS = ["matthieu", "marc", "luc", "jean"];

export function booksForCanon(canon) {
  return BOOKS.filter(b => b.canons.includes(canon));
}

export function isGospel(id) {
  return GOSPEL_IDS.includes(id);
}

export function bookHref(id, base = "", ref = null) {
  const file = GOSPEL_IDS.includes(id) ? `${id}.html` : `livre.html?livre=${id}`;
  let hash = "";
  if (ref && ref.chapter) {
    hash = `#c${ref.chapter}`;
    if (ref.verse) hash += `v${ref.verse}`;
  }
  return `${base}${file}${hash}`;
}

export function bookName(book) {
  if (!book) return "";
  return book.original_title || book.title || book.name || book.id || "";
}

export function neighborBooks(id, list = BOOKS) {
  const i = list.findIndex(b => b.id === id);
  return {
    prev: i > 0 ? list[i - 1] : null,
    next: i >= 0 && i < list.length - 1 ? list[i + 1] : null,
  };
}

export function versionIdsByYear(desc = false) {
  const yearOf = (id) => {
    const y = VERSIONS[id]?.year;
    return typeof y === "number" ? y : Number.POSITIVE_INFINITY;
  };
  const ids = Object.keys(VERSIONS);
  ids.sort((a, b) => (yearOf(a) - yearOf(b)) || a.localeCompare(b));
  return desc ? ids.reverse() : ids;
}
