#!/usr/bin/env python3
"""texts/{ls1910,vulgate,lxx}.json → data/livres + vulgate/septante + js/books.js."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from canon import BOOKS, BY_NR, SECTIONS

ROOT = Path(__file__).resolve().parents[1]
TEXTS = ROOT / "texts"
OUT_LS = ROOT / "data" / "livres"
OUT_VG = ROOT / "data" / "evangiles" / "vulgate"
OUT_LXX = ROOT / "data" / "evangiles" / "septante"
JS_BOOKS = ROOT / "js" / "books.js"

GOSPEL_IDS = {b["id"] for b in BOOKS if b["section"] == "evangiles"}

VERSIONS = {
    "segond-1910": {
        "id": "segond-1910",
        "label": "Traduction de Louis Segond · 1910",
        "license": "public-domain",
        "source": "Louis Segond 1910",
        "abbreviation": "ls1910",
    },
    "vulgate": {
        "id": "vulgate",
        "label": "Vulgate",
        "license": "public-domain",
        "source": "Vulgata Clementina",
        "abbreviation": "vulgate",
    },
    "septante": {
        "id": "septante",
        "label": "Septante",
        "license": "public-domain",
        "source": "OT LXX Accented",
        "abbreviation": "lxx",
    },
}


def clean(t: str) -> str:
    t = (t or "").replace("\u2009", " ").replace("\u00a0", " ")
    t = re.sub(r"<[^>]+>", "", t)
    return re.sub(r"[ \t]+", " ", t).strip()


def extract(src: Path, dest_dir: Path, version_key: str, *, skip_ids: set[str] | None = None) -> int:
    if not src.is_file():
        print(f"Missing {src}", file=sys.stderr)
        return 0
    raw = json.loads(src.read_text(encoding="utf-8"))
    by_nr = {b["nr"]: b for b in raw["books"] if b.get("nr") is not None}
    dest_dir.mkdir(parents=True, exist_ok=True)
    n = 0
    for meta in BOOKS:
        if skip_ids and meta["id"] in skip_ids:
            continue
        book_raw = by_nr.get(meta["nr"])
        if not book_raw:
            continue
        chapters = []
        for ch in book_raw["chapters"]:
            verses = [
                {"n": int(v["verse"]), "t": clean(v["text"])} for v in ch["verses"]
            ]
            chapters.append({"n": int(ch["chapter"]), "verses": verses})
        book = {
            "id": meta["id"],
            "title": meta["title"],
            "short": meta["short"],
            "version": VERSIONS[version_key],
            "chapters": chapters,
        }
        dest = dest_dir / f"{meta['id']}.json"
        dest.write_text(
            json.dumps(book, ensure_ascii=False, separators=(",", ":")),
            encoding="utf-8",
        )
        n_v = sum(len(c["verses"]) for c in chapters)
        print(f"{version_key:12} {meta['id']:20} {len(chapters):3} ch {n_v:5} v")
        n += 1
    return n


def write_books_js() -> None:
    helpers = """
export const BOOK_BY_ID = Object.fromEntries(BOOKS.map((b) => [b.id, b]));
export const GOSPEL_IDS = Object.freeze(
  BOOKS.filter((b) => b.section === "evangiles").map((b) => b.id)
);
export const SECTIONS = Object.freeze(%s);

export function isGospel(id) {
  return GOSPEL_IDS.includes(id);
}

export function bookHref(id, base = "") {
  if (isGospel(id)) return `${base}${id}.html#c1`;
  return `${base}livre.html?livre=${encodeURIComponent(id)}#c1`;
}

export function neighborBooks(id) {
  const i = BOOKS.findIndex((b) => b.id === id);
  if (i < 0) return { prev: null, next: null };
  return {
    prev: i > 0 ? BOOKS[i - 1] : null,
    next: i < BOOKS.length - 1 ? BOOKS[i + 1] : null,
  };
}
""" % json.dumps(
        [{"testament": t, "id": s, "label": lab} for t, s, lab in SECTIONS],
        ensure_ascii=False,
    )
    body = (
        "/** Generated by scripts/build-texts.py — do not edit. */\n"
        "export const BOOKS = "
        + json.dumps(BOOKS, ensure_ascii=False)
        + ";\n"
        + helpers
    )
    JS_BOOKS.write_text(body, encoding="utf-8")
    print(f"js/books.js {len(BOOKS)} books")


def main() -> int:
    write_books_js()
    n_ls = extract(TEXTS / "ls1910.json", OUT_LS, "segond-1910")
    n_vg = extract(TEXTS / "vulgate.json", OUT_VG, "vulgate")
    n_lxx = extract(TEXTS / "lxx.json", OUT_LXX, "septante", skip_ids=GOSPEL_IDS)
    print(f"done ls={n_ls} vulgate={n_vg} lxx={n_lxx}")
    if n_ls != 66:
        print(f"expected 66 LS books, got {n_ls}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
