"""Didactic book titles per language. Used as index.json `title`."""

CANON_PHRASE = {
    ("fr", "protestant"): "canon protestant",
    ("fr", "catholic"): "canon catholique",
    ("fr", "orthodox"): "canon orthodoxe",
    ("la", "protestant"): "canon protestanticum",
    ("la", "catholic"): "canon catholicum",
    ("la", "orthodox"): "canon orthodoxum",
    ("el", "protestant"): "κανὼν προτεσταντικός",
    ("el", "catholic"): "κανὼν καθολικός",
    ("el", "orthodox"): "κανὼν ὀρθόδοξος",
    ("fr", "jewish"): "canon hébraïque",
    ("he", "jewish"): "תנ״ך",
    ("he", "protestant"): "תנ״ך",
}

CANON_HEAD = {
    ("fr", "protestant"): "Canon protestant",
    ("fr", "catholic"): "Canon catholique",
    ("fr", "orthodox"): "Canon orthodoxe",
    ("la", "protestant"): "Canon protestanticum",
    ("la", "catholic"): "Canon catholicum",
    ("la", "orthodox"): "Canon orthodoxum",
    ("el", "protestant"): "Κανὼν προτεσταντικός",
    ("el", "catholic"): "Κανὼν καθολικός",
    ("el", "orthodox"): "Κανὼν ὀρθόδοξος",
    ("fr", "jewish"): "Canon hébraïque",
    ("he", "jewish"): "תנ״ך",
    ("he", "protestant"): "תנ״ך",
}

DIDACTIC = {
    "fr": {
        "genese": "Livre de la Genèse",
        "exode": "Livre de l'Exode",
        "levitique": "Livre du Lévitique",
        "nombres": "Livre des Nombres",
        "deuteronome": "Livre du Deutéronome",
        "josue": "Livre de Josué",
        "juges": "Livre des Juges",
        "ruth": "Livre de Ruth",
        "1-samuel": "Premier livre de Samuel",
        "2-samuel": "Second livre de Samuel",
        "1-rois": "Premier livre des Rois",
        "2-rois": "Second livre des Rois",
        "1-chroniques": "Premier livre des Chroniques",
        "2-chroniques": "Second livre des Chroniques",
        "esdras": "Livre d'Esdras",
        "nehemie": "Livre de Néhémie",
        "tobie": "Livre de Tobie",
        "judith": "Livre de Judith",
        "esther": "Livre d'Esther",
        "1-maccabees": "Premier livre des Maccabées",
        "2-maccabees": "Second livre des Maccabées",
        "3-maccabees": "Troisième livre des Maccabées",
        "4-maccabees": "Quatrième livre des Maccabées",
        "job": "Livre de Job",
        "psaumes": "Livre des Psaumes",
        "psaume-151": "Psaume 151",
        "proverbes": "Livre des Proverbes",
        "ecclesiaste": "L'Ecclésiaste",
        "cantique": "Cantique des cantiques",
        "sagesse": "Livre de la Sagesse",
        "siracide": "Siracide (Ecclésiastique)",
        "esaie": "Livre d'Ésaïe",
        "jeremie": "Livre de Jérémie",
        "lamentations": "Lamentations de Jérémie",
        "baruch": "Livre de Baruch",
        "ezechiel": "Livre d'Ézéchiel",
        "daniel": "Livre de Daniel",
        "osee": "Livre d'Osée",
        "joel": "Livre de Joël",
        "amos": "Livre d'Amos",
        "abdias": "Livre d'Abdias",
        "jonas": "Livre de Jonas",
        "michee": "Livre de Michée",
        "nahum": "Livre de Nahum",
        "habacuc": "Livre d'Habacuc",
        "sophonie": "Livre de Sophonie",
        "aggee": "Livre d'Aggée",
        "zacharie": "Livre de Zacharie",
        "malachie": "Livre de Malachie",
        "matthieu": "Évangile selon saint Matthieu",
        "marc": "Évangile selon saint Marc",
        "luc": "Évangile selon saint Luc",
        "jean": "Évangile selon saint Jean",
        "actes": "Actes des Apôtres",
        "romains": "Lettre de saint Paul Apôtre aux Romains",
        "1-corinthiens": "Première lettre de saint Paul Apôtre aux Corinthiens",
        "2-corinthiens": "Seconde lettre de saint Paul Apôtre aux Corinthiens",
        "galates": "Lettre de saint Paul Apôtre aux Galates",
        "ephesiens": "Lettre de saint Paul Apôtre aux Éphésiens",
        "philippiens": "Lettre de saint Paul Apôtre aux Philippiens",
        "colossiens": "Lettre de saint Paul Apôtre aux Colossiens",
        "1-thessaloniciens": "Première lettre de saint Paul Apôtre aux Thessaloniciens",
        "2-thessaloniciens": "Seconde lettre de saint Paul Apôtre aux Thessaloniciens",
        "1-timothee": "Première lettre de saint Paul Apôtre à Timothée",
        "2-timothee": "Seconde lettre de saint Paul Apôtre à Timothée",
        "tite": "Lettre de saint Paul Apôtre à Tite",
        "philemon": "Lettre de saint Paul Apôtre à Philémon",
        "hebreux": "Lettre aux Hébreux",
        "jacques": "Lettre de saint Jacques",
        "1-pierre": "Première lettre de saint Pierre Apôtre",
        "2-pierre": "Seconde lettre de saint Pierre Apôtre",
        "1-jean": "Première lettre de saint Jean",
        "2-jean": "Seconde lettre de saint Jean",
        "3-jean": "Troisième lettre de saint Jean",
        "jude": "Lettre de saint Jude",
        "apocalypse": "Apocalypse de saint Jean",
    },
    "la": {
        "genese": "Liber Genesis",
        "exode": "Liber Exodi",
        "levitique": "Liber Levitici",
        "nombres": "Liber Numerorum",
        "deuteronome": "Liber Deuteronomii",
        "josue": "Liber Iosue",
        "juges": "Liber Iudicum",
        "ruth": "Liber Ruth",
        "1-samuel": "Liber primus Samuelis",
        "2-samuel": "Liber secundus Samuelis",
        "1-rois": "Liber primus Regum",
        "2-rois": "Liber secundus Regum",
        "1-chroniques": "Liber primus Paralipomenon",
        "2-chroniques": "Liber secundus Paralipomenon",
        "esdras": "Liber Esdrae",
        "nehemie": "Liber Nehemiae",
        "tobie": "Liber Tobiae",
        "judith": "Liber Iudith",
        "esther": "Liber Esther",
        "1-maccabees": "Liber primus Machabaeorum",
        "2-maccabees": "Liber secundus Machabaeorum",
        "3-maccabees": "Liber tertius Machabaeorum",
        "4-maccabees": "Liber quartus Machabaeorum",
        "job": "Liber Iob",
        "psaumes": "Liber Psalmorum",
        "psaume-151": "Psalmus CLI",
        "proverbes": "Liber Proverbiorum",
        "ecclesiaste": "Liber Ecclesiastes",
        "cantique": "Canticum Canticorum",
        "sagesse": "Liber Sapientiae",
        "siracide": "Liber Ecclesiasticus",
        "esaie": "Liber Isaiae",
        "jeremie": "Liber Ieremiae",
        "lamentations": "Lamentationes Ieremiae",
        "baruch": "Liber Baruch",
        "ezechiel": "Liber Ezechielis",
        "daniel": "Liber Danielis",
        "osee": "Liber Osee",
        "joel": "Liber Ioel",
        "amos": "Liber Amos",
        "abdias": "Liber Abdiae",
        "jonas": "Liber Ionae",
        "michee": "Liber Michaeae",
        "nahum": "Liber Nahum",
        "habacuc": "Liber Habacuc",
        "sophonie": "Liber Sophoniae",
        "aggee": "Liber Aggaei",
        "zacharie": "Liber Zachariae",
        "malachie": "Liber Malachiae",
        "matthieu": "Evangelium secundum Matthaeum",
        "marc": "Evangelium secundum Marcum",
        "luc": "Evangelium secundum Lucam",
        "jean": "Evangelium secundum Ioannem",
        "actes": "Actus Apostolorum",
        "romains": "Epistula beati Pauli Apostoli ad Romanos",
        "1-corinthiens": "Epistula prima beati Pauli Apostoli ad Corinthios",
        "2-corinthiens": "Epistula secunda beati Pauli Apostoli ad Corinthios",
        "galates": "Epistula beati Pauli Apostoli ad Galatas",
        "ephesiens": "Epistula beati Pauli Apostoli ad Ephesios",
        "philippiens": "Epistula beati Pauli Apostoli ad Philippenses",
        "colossiens": "Epistula beati Pauli Apostoli ad Colossenses",
        "1-thessaloniciens": "Epistula prima beati Pauli Apostoli ad Thessalonicenses",
        "2-thessaloniciens": "Epistula secunda beati Pauli Apostoli ad Thessalonicenses",
        "1-timothee": "Epistula prima beati Pauli Apostoli ad Timotheum",
        "2-timothee": "Epistula secunda beati Pauli Apostoli ad Timotheum",
        "tite": "Epistula beati Pauli Apostoli ad Titum",
        "philemon": "Epistula beati Pauli Apostoli ad Philemonem",
        "hebreux": "Epistula ad Hebraeos",
        "jacques": "Epistula beati Iacobi Apostoli",
        "1-pierre": "Epistula prima beati Petri Apostoli",
        "2-pierre": "Epistula secunda beati Petri Apostoli",
        "1-jean": "Epistula prima beati Ioannis Apostoli",
        "2-jean": "Epistula secunda beati Ioannis Apostoli",
        "3-jean": "Epistula tertia beati Ioannis Apostoli",
        "jude": "Epistula beati Iudae Apostoli",
        "apocalypse": "Apocalypsis beati Ioannis Apostoli",
    },
    "el": {
        "genese": "Γένεσις",
        "exode": "Ἔξοδος",
        "levitique": "Λευϊτικόν",
        "nombres": "Ἀριθμοί",
        "deuteronome": "Δευτερονόμιον",
        "josue": "Ἰησοῦς Ναυῆ",
        "juges": "Κριταί",
        "ruth": "Ῥούθ",
        "1-samuel": "Βασιλειῶν Αʹ",
        "2-samuel": "Βασιλειῶν Βʹ",
        "1-rois": "Βασιλειῶν Γʹ",
        "2-rois": "Βασιλειῶν Δʹ",
        "1-chroniques": "Παραλειπομένων Αʹ",
        "2-chroniques": "Παραλειπομένων Βʹ",
        "esdras": "Ἔσδρας",
        "nehemie": "Νεεμίας",
        "tobie": "Τωβίτ",
        "judith": "Ἰουδίθ",
        "esther": "Ἐσθήρ",
        "1-maccabees": "Μακκαβαίων Αʹ",
        "2-maccabees": "Μακκαβαίων Βʹ",
        "3-maccabees": "Μακκαβαίων Γʹ",
        "4-maccabees": "Μακκαβαίων Δʹ",
        "job": "Ἰώβ",
        "psaumes": "Ψαλμοί",
        "psaume-151": "Ψαλμὸς ΡΝΑʹ",
        "proverbes": "Παροιμίαι",
        "ecclesiaste": "Ἐκκλησιαστής",
        "cantique": "Ἆσμα Ἀσμάτων",
        "sagesse": "Σοφία Σολομῶντος",
        "siracide": "Σοφία Σειράχ",
        "esaie": "Ἠσαΐας",
        "jeremie": "Ἰερεμίας",
        "lamentations": "Θρῆνοι",
        "baruch": "Βαρούχ",
        "ezechiel": "Ἰεζεκιήλ",
        "daniel": "Δανιήλ",
        "osee": "Ὡσηέ",
        "joel": "Ἰωήλ",
        "amos": "Ἀμώς",
        "abdias": "Ἀβδιού",
        "jonas": "Ἰωνᾶς",
        "michee": "Μιχαίας",
        "nahum": "Ναούμ",
        "habacuc": "Ἀμβακούμ",
        "sophonie": "Σοφονίας",
        "aggee": "Ἀγγαῖος",
        "zacharie": "Ζαχαρίας",
        "malachie": "Μαλαχίας",
        "matthieu": "Εὐαγγέλιον κατὰ Ματθαῖον",
        "marc": "Εὐαγγέλιον κατὰ Μᾶρκον",
        "luc": "Εὐαγγέλιον κατὰ Λουκᾶν",
        "jean": "Εὐαγγέλιον κατὰ Ἰωάννην",
        "actes": "Πράξεις τῶν Ἀποστόλων",
        "romains": "Πρὸς Ῥωμαίους ἐπιστολή",
        "1-corinthiens": "Πρὸς Κορινθίους ἐπιστολὴ πρώτη",
        "2-corinthiens": "Πρὸς Κορινθίους ἐπιστολὴ δευτέρα",
        "galates": "Πρὸς Γαλάτας ἐπιστολή",
        "ephesiens": "Πρὸς Ἐφεσίους ἐπιστολή",
        "philippiens": "Πρὸς Φιλιππησίους ἐπιστολή",
        "colossiens": "Πρὸς Κολοσσαεῖς ἐπιστολή",
        "1-thessaloniciens": "Πρὸς Θεσσαλονικεῖς ἐπιστολὴ πρώτη",
        "2-thessaloniciens": "Πρὸς Θεσσαλονικεῖς ἐπιστολὴ δευτέρα",
        "1-timothee": "Πρὸς Τιμόθεον ἐπιστολὴ πρώτη",
        "2-timothee": "Πρὸς Τιμόθεον ἐπιστολὴ δευτέρα",
        "tite": "Πρὸς Τίτον ἐπιστολή",
        "philemon": "Πρὸς Φιλήμονα ἐπιστολή",
        "hebreux": "Πρὸς Ἑβραίους ἐπιστολή",
        "jacques": "Ἰακώβου ἐπιστολή",
        "1-pierre": "Πέτρου ἐπιστολὴ πρώτη",
        "2-pierre": "Πέτρου ἐπιστολὴ δευτέρα",
        "1-jean": "Ἰωάννου ἐπιστολὴ πρώτη",
        "2-jean": "Ἰωάννου ἐπιστολὴ δευτέρα",
        "3-jean": "Ἰωάννου ἐπιστολὴ τρίτη",
        "jude": "Ἰούδα ἐπιστολή",
        "apocalypse": "Ἀποκάλυψις Ἰωάννου",
    },
    "he": {
        "genese": "בראשית",
        "exode": "שמות",
        "levitique": "ויקרא",
        "nombres": "במדבר",
        "deuteronome": "דברים",
        "josue": "יהושע",
        "juges": "שופטים",
        "ruth": "רות",
        "1-samuel": "שמואל א",
        "2-samuel": "שמואל ב",
        "1-rois": "מלכים א",
        "2-rois": "מלכים ב",
        "1-chroniques": "דברי הימים א",
        "2-chroniques": "דברי הימים ב",
        "esdras": "עזרא",
        "nehemie": "נחמיה",
        "esther": "אסתר",
        "job": "איוב",
        "psaumes": "תהלים",
        "proverbes": "משלי",
        "ecclesiaste": "קהלת",
        "cantique": "שיר השירים",
        "esaie": "ישעיהו",
        "jeremie": "ירמיהו",
        "lamentations": "איכה",
        "ezechiel": "יחזקאל",
        "daniel": "דניאל",
        "osee": "הושע",
        "joel": "יואל",
        "amos": "עמוס",
        "abdias": "עובדיה",
        "jonas": "יונה",
        "michee": "מיכה",
        "nahum": "נחום",
        "habacuc": "חבקוק",
        "sophonie": "צפניה",
        "aggee": "חגי",
        "zacharie": "זכריה",
        "malachie": "מלאכי",
    },
}

HEBREW_ORIGINAL = DIDACTIC["he"]


def didactic_title(lang: str, book_id: str, fallback: str) -> str:
    table = DIDACTIC.get(lang) or DIDACTIC["fr"]
    return table.get(book_id) or fallback


def canon_phrase(lang: str, canon: str) -> str:
    return CANON_PHRASE.get((lang, canon)) or CANON_PHRASE.get(("fr", canon)) or canon


def canon_head(lang: str, canon: str) -> str:
    return CANON_HEAD.get((lang, canon)) or CANON_HEAD.get(("fr", canon)) or canon
